version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web_data:/var/www/html
      - ./src:/var/www/html
      - ./default.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./default.conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      a_network:
        ipv4_address: 192.168.40.2

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    networks:
      a_network:
        ipv4_address: 192.168.40.3


networks:
  a_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.40.0/24

volumes:
  web_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/www/html'
  mysql_backup:
    driver: local